name: Docker Image CI

on:
  push:
    branches:
      - dev-prod-backend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend code
        uses: actions/checkout@v2

      - name: Checkout frontend code
        uses: actions/checkout@v2
        with:
          repository: metrolabsservices/aarshafrontend
          ref: dev-prod-frontned
          path: frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cir.dev.vaaradhiitservices.com//aarsha:latest
